name: Setup
runs:
  using: "composite"
  steps:
    - name: Mark Repo as Safe
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      shell: sh
    - name: Cache CMake files
      id: cache-cmake
      uses: actions/cache@v5
      env:
        cache-name: cache-cmake
      with:
        path: ./build
        key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
    - name: Generate CMake cache
      if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      run: |
        cmake --preset Debug -G Ninja
        cmake --preset Release -G Ninja
      shell: sh
